
permalink: none
# Build settings
markdown: kramdown

include: ['.htaccess']

lang: de

# baseurl: '/LB-singt'
baseurl: ''
url: 'https://lb-singt.de'

authors: 'STADTVERBAND MUSIK Ludwigsburg 1966 e.V'

title: 'Ludwigsburg singt wieder!'

description: 'Singen Sie mit, am 3. Oktober 2021, in der Friedenskirche Ludwigsburg.'

keywords: 'Ludwigsburg, Chor, Singen, Friedenskirche, Prof. Siegfried Bauer'

social_image_path: '/assets/img/posts/frauenChor-final.jpg'

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- LICENSE
- README.md
- myNotes

sass:
  style: :compressed

bootstrap:
  assets: false
